### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by vershart** [dknight/Isikukood-js#29]
Thank you for your library!
That would be great to include TypeScript definition files in your library.

**Comment by dknight** [comment]
Not a big fan of TypeScript, maybe later I will rewrite this in TypeScript, only because of this is so called "mainstream". Lets see a bit later, at the moment I am bit busy on my main job. If you wish you can of course do it yourself and make PR. I don't give any promises when I will do this.

**Comment by simplysexyboy** [comment]
is there any tutorial how to make it works? when i download the files and run on local just generating random number i want to add spesific gender and bday..

**Comment by dknight** [comment]
Yes this is correct.

**Comment by dknight** [comment]
Finally migrate to TypeScript. 
Version bumped to 3.0.0
